Vagrant.configure("2") do |config|

  # config.vm.boot_mode = :gui
  
  # CloudStack Management Server
  config.vm.define :management01 do |management|    

    management.vm.box = 'CloudStack-4.2-CentOS-6.4-x86_64'
    management.vm.box_url = '' # CloudStack-4.2-CentOS-6.4-x86_64
    management.vm.hostname = 'management01'    
    management.vm.synced_folder ".", "/vagrant", :disabled => true

    # Guest Network
    management.vm.network :private_network, ip: '10.1.100.10'
    # Management Network
    management.vm.network :private_network, ip: '10.10.100.10'
    # Storage Network
    management.vm.network :private_network, ip: '172.16.100.10'
    # Public Network
    management.vm.network :private_network, ip: '192.168.100.10'

    management.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]   
    end    
  end
  
  # CloudStack Node Server
  config.vm.define :node01 do |node|

    node.vm.box = 'XenServer-6.2'
    node.vm.box_url = 'https://mega.co.nz/#!7YEWgRZL!M1KLN1b6nAydZcrI1WQW4iZL3hE3phJaiGNqxpFNfP4' # XenServer-6.2.box
    node.vm.hostname = 'node01'    
    node.vm.synced_folder ".", "/vagrant", :disabled => true

    # Guest Network
    node.vm.network :private_network, ip: '10.1.100.20'
    # Management Network
    node.vm.network :private_network, ip: '10.10.100.20'
    # Storage Network
    node.vm.network :private_network, ip: '172.16.100.20'
    # Public Network
    node.vm.network :private_network, ip: '192.168.100.20'
    
    node.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4096"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]   
    end
  end

  # FreeNas-9.1.1
  config.vm.define :freenas do |freenas|    

    freenas.vm.box = 'FreeNas-9.1.1'
    freenas.vm.box_url = '' # FreeNas-9.1.1.box

    # Storage Network
    freenas.vm.network :private_network, ip: '172.16.100.2'

    freenas.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]   
    end    
  end

  # openfileresa-2.99.1-x86_64
  config.vm.define :openfiler do |openfiler|    

    openfiler.vm.box = 'openfileresa-2.99.1-x86_64'
    openfiler.vm.box_url = '' # openfileresa-2.99.1-x86_64.box
    openfiler.vm.hostname = 'openfiler'

    # Storage Network
    openfiler.vm.network :private_network, ip: '172.16.100.3'

    openfiler.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]   
    end    
  end

  # CentOS-6.4-x86_64-minimal
  config.vm.define :centos do |centos|

    centos.vm.box = 'CentOS-6.4-x86_64-minimal'
    centos.vm.box_url = 'https://mega.co.nz/#!2RUi0K7Q!DADgrEw3LGKNrDycbR1cKScHtVBi-aIgkjqnXjXmUUc' # CentOS-6.4-x86_64-minimal.box
    centos.vm.hostname = 'centos'

    # Guest Network
    centos.vm.network :private_network, ip: '10.1.100.2'

    centos.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]   
    end    
  end

  
end
